### ISSUE TITLE
BeamNG sees wheel but does not detect input

### ISSUE THREAD

**Issue by krims0n32** [Kimplul/hid-tmff2#106]
I cannot get my T300RS to work with BeamNG. The game sees the wheel but does not detect any input at all. It does detect input on my Virpil controls however. If I set the wheel to PS4 mode input does work but some buttons and the shifter pedals do not work. Any ideas?

Edit: I see there are similar issues reported already regarding proton, sorry for not checking those first. I have one question still though, I am supposed to set the wheel to PC mode correct?

**Comment by Kimplul** [comment]
> I see there are similar issues reported already regarding proton, sorry for not checking those first.

No worries. Sounds like it's OK to close this issue, but feel free to chime in on the other ones.

> I am supposed to set the wheel to PC mode correct?

PC mode is generally recommended, but there is support for the PS4 mode as well, just less tested.

**Comment by krims0n32** [comment]
I tried PS4/PS5 mode again and now it works all of a sudden. Tried ACC and BeamNG. Force feedback also works.

Thanks for your work on this driver!
