### ISSUE TITLE
Does not work on bazzite.

### ISSUE THREAD

**Issue by Iwo24pl** [Kimplul/hid-tmff2#133]
How can i install it on bazzite? is shows some kernel issues.

**Comment by Kimplul** [comment]
Haven't tried Bazzite, please show the commands and output that you tried, including the error message(s). Preferably as just raw text within a code block.

**Comment by Iwo24pl** [comment]
make -C deps/hid-tminit KDIR="/lib/modules/6.11.10-304.bazzite.fc41.x86_64/build" 
make[1]: *Enter to catalog '/var/home/iwo/hid-tmff2/deps/hid-tminit'
make -C /lib/modules/6.11.10-304.bazzite.fc41.x86_64/build M=/var/home/iwo/hid-tmff2/deps/hid-tminit modules
make[2]: *Enter to catalog '/var/home/iwo/hid-tmff2/deps/hid-tminit'
make[2]: *** /lib/modules/6.11.10-304.bazzite.fc41.x86_64/build: Nie ma takiego pliku ani katalogu. Stop.
make[2]: *Exiting catalog '/var/home/iwo/hid-tmff2/deps/hid-tminit'
make[1]: *** [Makefile:4: all] Błąd 2
make[1]: *Exiting catalog '/var/home/iwo/hid-tmff2/deps/hid-tminit'
make: *** [Makefile:20: deps/hid-tminit] *Error 2

**Comment by Iwo24pl** [comment]
Single * = translated from Polish

**Comment by Iwo24pl** [comment]
Also Bazzite is based on Fedora Atomic, so I'm not sure if it will work, because its an ostree-based os

**Comment by Iwo24pl** [comment]
I just installed Linux Mint. Most of the apps did not work on Bazzite.

**Comment by Iwo24pl** [comment]
-

**Comment by Iwo24pl** [comment]
I had them installed.

**Comment by Iwo24pl** [comment]
On normal Fedora there is dims, not on atomic
