### ISSUE TITLE
T300RS Firmware v.34

### ISSUE THREAD

**Issue by sayapinsergej** [Kimplul/hid-tmff2#41]
Does this driver work on the latest firmware v.34?

**Comment by Kimplul** [comment]
Haven't tested personally, have you had issues?

**Comment by sayapinsergej** [comment]
I didn't test it, I wanted to find out how it works

**Comment by Kimplul** [comment]
Fair enough. Can't test at the moment and won't be able to for a little while, if you or someone else finds that it works feel free to update this thread.

**Comment by Raboebie** [comment]
I'll let you know in an hour or two. Flashed the firmware just now.

**Comment by Kimplul** [comment]
Thanks!

**Comment by Raboebie** [comment]
@Kimplul I'm happy to help you maintain/assists with this driver if needed. Contact me if you feel so inclined :+1:

**Comment by sayapinsergej** [comment]
good news! thank you!

**Comment by sayapinsergej** [comment]
Raspbian Buster with all updates
apt install linux-headers-$(uname -r).
I get the following:
E: Unable to locate package linux-headers-5.103
E: Couldn't find any package by glob 'linux-headers-5.103'
E: Couldn't find any package by regex 'linux-headers-5.103'
how to fix it?

**Comment by Raboebie** [comment]
You are missing linux-headers for you running kernel.

sudo apt install linux-headers-$(uname -r)

**Comment by sayapinsergej** [comment]
Yes, I added sudo

**Comment by sayapinsergej** [comment]
thanks for the article, I do everything as described there, but I still encounter an error:
sudo apt install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-5.10.103
E: Couldn't find any package by glob 'linux-headers-5.10.103'
E: Couldn't find any package by regex 'linux-headers-5.10.103'

**Comment by Kimplul** [comment]
AFrom raspbian I'm guessing you're running a raspberry pi? They have their own kernel headers, `apt install raspberrypi-kernel-headers`.

Out of curiosity, why are you doing it on a pi?

**Comment by sayapinsergej** [comment]
yes, I use raspberry pi. For GIMX to work, but thrustmaster does not work correctly with linux...

**Comment by Kimplul** [comment]
Oh cool, hadn't heard about GIMX before. Hope the driver works on arm, it did compile and do something in `fftest` the last time I checked but that was a while ago. Keep me updated.
