### ISSUE TITLE
Loading hid-tmff with secure boot enabled

### ISSUE THREAD

**Issue by SnoutBug** [Kimplul/hid-tmff2#62]
The hid_tmff_new module won't load when secure boot is enabled.

I'm not exactly sure how kernel modules work: Is it correct that you can prevent this by following the optional signing step you described with the manual installation procedure?

**Comment by Kimplul** [comment]
> I'm not exactly sure how kernel modules work: Is it correct that you can prevent this by following the optional signing step you described with the manual installation procedure?

Yep, secure boot essentially disables loading untrusted modules. To make a module trusted, you have to sign it.

**Comment by SnoutBug** [comment]
>Yep, secure boot essentially disables loading untrusted modules. To make a module trusted, you have to sign it.

Thanks  a bunch.

Signing the module was pretty straight forward with DKMS using [this gist](https://gist.github.com/dojoe/2a9e2dddca982c4f679552fc1ebb18df). The module is now working as intended!
