### ISSUE TITLE
T128

### ISSUE THREAD

**Issue by Sylv1pons** [Kimplul/hid-tmff2#75]
![20231115_194215](https://github.com/Kimplul/hid-tmff2/assets/79605266/394aaf96-35bb-4f5c-ae96-144d070b7ccb)
Lsusb for T128

**Comment by Kimplul** [comment]
Hello, I assume you would like this driver to support the T128? There's already an open issue about it, see https://github.com/Kimplul/hid-tmff2/issues/67

I'll close this issue but feel free to participate over in #67. Out of curiosity, are you attempting to set up GIMX on a raspberry pi or something, or why are you connecting to Linux through putty?

By the way, posting screenshots/pictures of screens of text is usually frowned upon, please consider copypasting the text instead. Helps people who interact through email and so on.

**Comment by Sylv1pons** [comment]
I use Batocera on x86_64 on V39 with the steering wheel

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
