### ISSUE TITLE
T300RS GT Edition?

### ISSUE THREAD

**Issue by melroy89** [Kimplul/hid-tmff2#80]
It's a bit unclear and undocumented. But is Is T300RS GT Edition support as well? Or only T300RS? If so, you might want to update your readme/descriptions.

**Comment by Kimplul** [comment]
> [...] is T300RS GT Edition support as well? [...]

It probably works, as it seems like the T300RS series all use the same base with different wheel attachments. At least there's some evidence that someone has managed to use the GT version: https://github.com/Kimplul/hid-tmff2/issues/31#issuecomment-1279829350

That being said, I personally only have the base RS version, so I guess can't really say that I 'support' the GT edition, only the base wheel, and if other editions work then that's of course great. I'll try to solve issues for other editions as well, but that would be on a best-effort basis. Probably worth mentioning in the README somewhere, you're right.
