### ISSUE TITLE
Is it safe to install with DKMS after having manually installed?

### ISSUE THREAD

**Issue by dlmw** [Kimplul/hid-tmff2#92]
Is it safe to install with DKMS after having manually installed? Should I uninstall the modules first? But how do I uninstall it? 😟

**Comment by Kimplul** [comment]
Yep, perfectly safe. Linux will generally just ignore duplicate modules, and the next time your kernel gets updated, DKMS will remain as the only active module so the issue resolves itself, no real need to manually uninstall anything. Generally your distro will also automatically uninstall kernel versions that are older than some threshold, which automatically gets rid of any extra modules.

If you still want to manually uninstall, remove the `hid-tmff-new.ko` and `hid-tminit.ko` files in `/usr/lib/modules/$KERNEL_VERSION/extra/`. Each kernel version has its own copy of the modules, so you may have multiple directories to go through, but again, this is generally not necessary.
